<Project Sdk="Aspire.AppHost.Sdk/13.2.4">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>e6097a24-6da6-4b2a-94bb-4edde32f6eee</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FirstWebApi.Server\FirstWebApi.Server.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.JavaScript" Version="13.2.4" />
  </ItemGroup>
</Project>
